services:
  hamerkop:
    image: localhost/charlieroth/hamerkop:0.1.0
    pull_policy: never
    container_name: hamerkop
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 2s
    cpu_count: 2
    environment:
      - GOMAXPROCS=2
    expose:
      - "8080:8080"
    volumes:
      - ./db:/app/db
    deploy:
      resources:
        limits:
          # https://docs.docker.com/reference/compose-file/deploy/#memory
          memory: 2GB
